service: products-management
useDotenv: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-common-excludes

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-southeast-1
  stage: ${opt:stage, 'dev'}
  deploymentBucket: ${env:S3_BUCKET_NAME}
  deploymentPrefix: ${env:DEPLOYMENT_BUCKET_PREFIX}
  memorySize: 256
  timeout: 30

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:DeleteObject
        - s3:DeleteObjects
      Resource:
        - arn:aws:s3:::${env:S3_BUCKET_NAME}/*
    - Effect: Allow
      Action:
        - s3:ListBucket
      Resource:
        - arn:aws:s3:::${env:S3_BUCKET_NAME}/*
        - arn:aws:s3:::${env:S3_BUCKET_NAME}
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource:
        - arn:aws:secretsmanager:${aws:region}:${aws:accountId}:secret:jwt-secret-*

  tags:
    PROJECT: products-management
    ENVIRONMENT: ${self:provider.stage}
    DEVELOPER: quan.tranvan
    VERSION: v0.1

functions:
  api:
    handler: dist/src/main.handler
    timeout: 30
    memorySize: 512
    events:
      - http: ANY /{proxy+}

custom:
  currentStage: ${self:provider.stage}
  webpack:
    packager: yarn
    includeModules: true
